import { SourceCategory, TopicDomain } from "@/lib/types";

export interface SourceProfile {
  name: string;
  urlTemplate: (query: string) => string;
  sourceCategory: SourceCategory;
  domain: TopicDomain;
  authorityScore: number;
  freshnessScore: number;
  formatFitScore: number;
  whySelected: string;
  supports: string[];
  excerpt: string;
}

export interface MentionableSourceProfile {
  name: string;
  aliases: string[];
  url: string;
  sourceCategory: SourceCategory;
  domain: TopicDomain;
  authorityScore: number;
  freshnessScore: number;
  formatFitScore: number;
  whySelected: string;
  supports: string[];
  excerpt: string;
}

export const SOURCE_PROFILES: Record<TopicDomain, SourceProfile[]> = {
  travel: [
    {
      name: "Tripadvisor",
      urlTemplate: (query) => `https://www.tripadvisor.com/Search?q=${encodeURIComponent(query)}`,
      sourceCategory: "reviews",
      domain: "travel",
      authorityScore: 7,
      freshnessScore: 8,
      formatFitScore: 9,
      whySelected: "Traveler reviews help validate popularity, reputation, and common recommendations.",
      supports: ["traveler reviews", "popularity"],
      excerpt: "Use traveler reviews and rankings to validate attraction popularity and user sentiment.",
    },
    {
      name: "Google Maps",
      urlTemplate: (query) => `https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(query)}`,
      sourceCategory: "maps",
      domain: "travel",
      authorityScore: 8,
      freshnessScore: 9,
      formatFitScore: 9,
      whySelected: "Maps validate whether places are real, active, and correctly located.",
      supports: ["location", "listing validation"],
      excerpt: "Use map listings to confirm locations, categories, hours, and existence.",
    },
    {
      name: "Lonely Planet",
      urlTemplate: (query) => `https://www.lonelyplanet.com/search?q=${encodeURIComponent(query)}`,
      sourceCategory: "editorial-guide",
      domain: "travel",
      authorityScore: 8,
      freshnessScore: 7,
      formatFitScore: 9,
      whySelected: "Widely trusted destination guides for attraction and itinerary validation.",
      supports: ["editorial recommendations", "destination overview"],
      excerpt: "Cross-reference destination guides and top attraction lists from a widely trusted travel publisher.",
    },
    {
      name: "Yelp",
      urlTemplate: (query) => `https://www.yelp.com/search?find_desc=${encodeURIComponent(query)}`,
      sourceCategory: "reviews",
      domain: "travel",
      authorityScore: 6,
      freshnessScore: 8,
      formatFitScore: 8,
      whySelected: "Useful for local restaurant and attraction validation via user reviews.",
      supports: ["local reviews", "dining"],
      excerpt: "Use Yelp to validate local restaurant, attraction, and neighborhood recommendations.",
    },
  ],
  "tech-learning": [
    {
      name: "MDN Web Docs",
      urlTemplate: (query) => `https://developer.mozilla.org/en-US/search?q=${encodeURIComponent(query)}`,
      sourceCategory: "official-docs",
      domain: "tech-learning",
      authorityScore: 10,
      freshnessScore: 8,
      formatFitScore: 9,
      whySelected: "Primary reference for web platform concepts and APIs.",
      supports: ["definitions", "technical accuracy", "examples"],
      excerpt: "Use MDN to validate web concepts, APIs, and core frontend learning topics.",
    },
    {
      name: "freeCodeCamp",
      urlTemplate: (query) => `https://www.freecodecamp.org/news/search/?query=${encodeURIComponent(query)}`,
      sourceCategory: "tutorial",
      domain: "tech-learning",
      authorityScore: 8,
      freshnessScore: 7,
      formatFitScore: 9,
      whySelected: "Useful for beginner-friendly learning paths and practical coding tutorials.",
      supports: ["learning roadmap", "beginner tutorial"],
      excerpt: "Use tutorials and learning-path articles to support beginner coding guidance.",
    },
    {
      name: "GitHub",
      urlTemplate: (query) => `https://github.com/search?q=${encodeURIComponent(query)}&type=repositories`,
      sourceCategory: "open-source",
      domain: "tech-learning",
      authorityScore: 8,
      freshnessScore: 8,
      formatFitScore: 8,
      whySelected: "Open-source repos help validate tooling, starter projects, and ecosystem reality.",
      supports: ["implementation examples", "starter projects"],
      excerpt: "Use GitHub to find example repos and validate real-world ecosystem support.",
    },
    {
      name: "Stack Overflow",
      urlTemplate: (query) => `https://stackoverflow.com/search?q=${encodeURIComponent(query)}`,
      sourceCategory: "developer-discussion",
      domain: "tech-learning",
      authorityScore: 6,
      freshnessScore: 7,
      formatFitScore: 8,
      whySelected: "Useful for common pain points and practical beginner troubleshooting.",
      supports: ["common questions", "developer discussion"],
      excerpt: "Use developer Q&A to sanity-check common questions and real-world friction points.",
    },
    {
      name: "dev.to",
      urlTemplate: (query) => `https://dev.to/search?q=${encodeURIComponent(query)}`,
      sourceCategory: "tutorial",
      domain: "tech-learning",
      authorityScore: 6,
      freshnessScore: 8,
      formatFitScore: 8,
      whySelected: "Practitioner blog posts with real-world coding perspectives.",
      supports: ["experience-based tutorials", "community advice"],
      excerpt: "Use dev.to for practical, experience-based developer perspectives and tutorials.",
    },
    {
      name: "Codecademy",
      urlTemplate: (query) => `https://www.codecademy.com/search?query=${encodeURIComponent(query)}`,
      sourceCategory: "tutorial",
      domain: "tech-learning",
      authorityScore: 8,
      freshnessScore: 7,
      formatFitScore: 9,
      whySelected: "Structured beginner learning paths and interactive coding lessons.",
      supports: ["interactive learning", "beginner tutorial"],
      excerpt: "Use Codecademy for structured beginner lessons and skill-building roadmaps.",
    },
    {
      name: "Coursera",
      urlTemplate: (query) => `https://www.coursera.org/search?query=${encodeURIComponent(query)}`,
      sourceCategory: "tutorial",
      domain: "tech-learning",
      authorityScore: 8,
      freshnessScore: 7,
      formatFitScore: 9,
      whySelected: "Strong source for structured courses and guided beginner programs.",
      supports: ["course pathway", "structured learning"],
      excerpt: "Use Coursera to validate course-based learning paths and beginner-friendly programs.",
    },
    {
      name: "HackerRank",
      urlTemplate: (query) => `https://www.hackerrank.com/search?search=${encodeURIComponent(query)}`,
      sourceCategory: "tutorial",
      domain: "tech-learning",
      authorityScore: 7,
      freshnessScore: 8,
      formatFitScore: 8,
      whySelected: "Useful for practice-oriented coding progression and challenge-based learning.",
      supports: ["practice", "coding challenges"],
      excerpt: "Use HackerRank to validate coding practice workflows and challenge-based skill building.",
    },
    {
      name: "LeetCode",
      urlTemplate: (query) => `https://leetcode.com/problemset/?search=${encodeURIComponent(query)}`,
      sourceCategory: "tutorial",
      domain: "tech-learning",
      authorityScore: 7,
      freshnessScore: 8,
      formatFitScore: 8,
      whySelected: "Useful for interview practice and consistency-based coding repetition.",
      supports: ["practice", "interview preparation"],
      excerpt: "Use LeetCode to validate repetition-based practice and coding challenge recommendations.",
    },
  ],
  "ai-infra": [
    {
      name: "GitHub",
      urlTemplate: (query) => `https://github.com/search?q=${encodeURIComponent(query)}&type=repositories`,
      sourceCategory: "open-source",
      domain: "ai-infra",
      authorityScore: 9,
      freshnessScore: 9,
      formatFitScore: 9,
      whySelected: "GitHub validates whether the protocol or tool has a living implementation or reference repo.",
      supports: ["implementation", "reference repo"],
      excerpt: "Use GitHub to validate active implementations, SDKs, or reference specifications.",
    },
    {
      name: "Hugging Face",
      urlTemplate: (query) => `https://huggingface.co/search/full-text?q=${encodeURIComponent(query)}`,
      sourceCategory: "official-docs",
      domain: "ai-infra",
      authorityScore: 9,
      freshnessScore: 9,
      formatFitScore: 9,
      whySelected: "Central hub for models, datasets, and AI tooling documentation.",
      supports: ["model validation", "AI tooling"],
      excerpt: "Use Hugging Face to validate models, embeddings, and AI infrastructure claims.",
    },
    {
      name: "Papers With Code",
      urlTemplate: (query) => `https://paperswithcode.com/search?q_meta=&q_type=&q=${encodeURIComponent(query)}`,
      sourceCategory: "spec",
      domain: "ai-infra",
      authorityScore: 8,
      freshnessScore: 9,
      formatFitScore: 8,
      whySelected: "Links research papers to real implementations for grounding AI claims.",
      supports: ["research grounding", "benchmark validation"],
      excerpt: "Use Papers With Code to validate AI research claims with linked implementations.",
    },
    {
      name: "Stack Overflow",
      urlTemplate: (query) => `https://stackoverflow.com/search?q=${encodeURIComponent(query)}`,
      sourceCategory: "developer-discussion",
      domain: "ai-infra",
      authorityScore: 5,
      freshnessScore: 7,
      formatFitScore: 7,
      whySelected: "Useful secondary source for practical pain points once primary sources are covered.",
      supports: ["practical discussion"],
      excerpt: "Use community discussion as a secondary source after primary docs and repos.",
    },
  ],
  health: [
    {
      name: "CDC",
      urlTemplate: (query) => `https://search.cdc.gov/search/?query=${encodeURIComponent(query)}`,
      sourceCategory: "government",
      domain: "health",
      authorityScore: 9,
      freshnessScore: 8,
      formatFitScore: 8,
      whySelected: "Strong public-health source for broad guidance and factual grounding.",
      supports: ["public guidance", "health basics"],
      excerpt: "Use CDC guidance to ground broad health and wellness claims.",
    },
    {
      name: "MedlinePlus",
      urlTemplate: (query) => `https://medlineplus.gov/search/?query=${encodeURIComponent(query)}`,
      sourceCategory: "peer-reviewed",
      domain: "health",
      authorityScore: 10,
      freshnessScore: 8,
      formatFitScore: 8,
      whySelected: "High-trust NIH reference for medical and health education topics.",
      supports: ["definitions", "clinical guidance"],
      excerpt: "Use medical reference sources for explanatory health education and evidence-backed claims.",
    },
    {
      name: "Mayo Clinic",
      urlTemplate: (query) => `https://www.mayoclinic.org/search/search-results?q=${encodeURIComponent(query)}`,
      sourceCategory: "editorial-guide",
      domain: "health",
      authorityScore: 8,
      freshnessScore: 8,
      formatFitScore: 8,
      whySelected: "Mainstream clinical reference for symptoms, habits, and wellness language.",
      supports: ["symptoms", "habit guidance"],
      excerpt: "Use mainstream clinical references to cross-check symptoms and wellness language.",
    },
    {
      name: "PubMed",
      urlTemplate: (query) => `https://pubmed.ncbi.nlm.nih.gov/?term=${encodeURIComponent(query)}`,
      sourceCategory: "peer-reviewed",
      domain: "health",
      authorityScore: 10,
      freshnessScore: 8,
      formatFitScore: 7,
      whySelected: "Peer-reviewed research for evidence-based health and nutrition claims.",
      supports: ["research backing", "clinical evidence"],
      excerpt: "Use peer-reviewed research to back evidence-based health, nutrition, and fitness claims.",
    },
  ],
  finance: [
    {
      name: "Investopedia",
      urlTemplate: (query) => `https://www.investopedia.com/search#q=${encodeURIComponent(query)}`,
      sourceCategory: "editorial-guide",
      domain: "finance",
      authorityScore: 8,
      freshnessScore: 7,
      formatFitScore: 8,
      whySelected: "Useful for beginner-friendly finance terminology and explainers.",
      supports: ["definitions", "finance basics"],
      excerpt: "Use finance explainers to ground terminology and beginner-friendly money topics.",
    },
    {
      name: "NerdWallet",
      urlTemplate: (query) => `https://www.nerdwallet.com/search?q=${encodeURIComponent(query)}`,
      sourceCategory: "editorial-guide",
      domain: "finance",
      authorityScore: 7,
      freshnessScore: 8,
      formatFitScore: 8,
      whySelected: "Consumer finance advice for budgeting, credit, and savings topics.",
      supports: ["consumer guidance", "product comparison"],
      excerpt: "Use NerdWallet for budgeting, credit card, and savings rate comparisons.",
    },
    {
      name: "Consumer Financial Protection Bureau",
      urlTemplate: (query) => `https://www.consumerfinance.gov/search/?q=${encodeURIComponent(query)}`,
      sourceCategory: "government",
      domain: "finance",
      authorityScore: 9,
      freshnessScore: 8,
      formatFitScore: 8,
      whySelected: "Strong public guidance for debt, credit, and savings basics.",
      supports: ["consumer guidance", "credit", "debt"],
      excerpt: "Use official consumer finance guidance for debt, credit, and savings claims.",
    },
    {
      name: "IRS",
      urlTemplate: (query) => `https://www.irs.gov/search?q=${encodeURIComponent(query)}`,
      sourceCategory: "government",
      domain: "finance",
      authorityScore: 10,
      freshnessScore: 8,
      formatFitScore: 7,
      whySelected: "Best source when the topic touches taxes or official financial rules.",
      supports: ["tax rules", "official definitions"],
      excerpt: "Use official IRS guidance for tax, retirement account, and filing-related claims.",
    },
  ],
  recipe: [
    {
      name: "Serious Eats",
      urlTemplate: (query) => `https://www.seriouseats.com/search?q=${encodeURIComponent(query)}`,
      sourceCategory: "recipe-editorial",
      domain: "recipe",
      authorityScore: 8,
      freshnessScore: 7,
      formatFitScore: 9,
      whySelected: "Strong source for technique-heavy recipe validation.",
      supports: ["technique", "ingredient reasoning"],
      excerpt: "Use technique-heavy recipe sources to validate cooking methods and ingredient logic.",
    },
    {
      name: "Allrecipes",
      urlTemplate: (query) => `https://www.allrecipes.com/search?q=${encodeURIComponent(query)}`,
      sourceCategory: "recipe-editorial",
      domain: "recipe",
      authorityScore: 7,
      freshnessScore: 7,
      formatFitScore: 8,
      whySelected: "Mainstream ingredient lists, timing, and recipe comparisons.",
      supports: ["ingredient validation", "timing"],
      excerpt: "Use mainstream recipe references to validate ingredients, timing, and preparation expectations.",
    },
    {
      name: "Food Network",
      urlTemplate: (query) => `https://www.foodnetwork.com/search/${encodeURIComponent(query)}-`,
      sourceCategory: "recipe-editorial",
      domain: "recipe",
      authorityScore: 7,
      freshnessScore: 7,
      formatFitScore: 8,
      whySelected: "Useful for mainstream recipe validation and chef-backed culinary framing.",
      supports: ["mainstream recipe validation"],
      excerpt: "Use Food Network to cross-check recipe names, ingredient sets, and meal ideas.",
    },
  ],
  general: [
    {
      name: "Wikipedia",
      urlTemplate: (query) => `https://en.wikipedia.org/w/index.php?search=${encodeURIComponent(query)}`,
      sourceCategory: "encyclopedia",
      domain: "general",
      authorityScore: 5,
      freshnessScore: 5,
      formatFitScore: 5,
      whySelected: "Useful for background context and quick topic orientation.",
      supports: ["background context"],
      excerpt: "Use an encyclopedia overview to orient around the topic and discover primary sources.",
    },
    {
      name: "Reddit",
      urlTemplate: (query) => `https://www.reddit.com/search/?q=${encodeURIComponent(query)}`,
      sourceCategory: "search-fallback",
      domain: "general",
      authorityScore: 4,
      freshnessScore: 8,
      formatFitScore: 6,
      whySelected: "Community perspectives and real-world discussion when no specialist source fits.",
      supports: ["community discussion", "real-world perspectives"],
      excerpt: "Use Reddit for community-sourced discussion and real-world perspectives on general topics.",
    },
  ],
};

export const MENTIONABLE_SOURCE_PROFILES: MentionableSourceProfile[] = [
  {
    name: "MDN Web Docs",
    aliases: ["mdn", "mdn web docs"],
    url: "https://developer.mozilla.org/en-US/",
    sourceCategory: "official-docs",
    domain: "tech-learning",
    authorityScore: 10,
    freshnessScore: 8,
    formatFitScore: 9,
    whySelected: "Primary reference for web platform concepts and APIs.",
    supports: ["definitions", "technical accuracy", "examples"],
    excerpt: "Use MDN to validate web concepts, APIs, and core frontend learning topics.",
  },
  {
    name: "freeCodeCamp",
    aliases: ["freecodecamp", "free code camp"],
    url: "https://www.freecodecamp.org/",
    sourceCategory: "tutorial",
    domain: "tech-learning",
    authorityScore: 8,
    freshnessScore: 7,
    formatFitScore: 9,
    whySelected: "Beginner-friendly learning paths and practical coding tutorials.",
    supports: ["learning roadmap", "beginner tutorial"],
    excerpt: "Use tutorials and learning-path articles to support beginner coding guidance.",
  },
  {
    name: "Codecademy",
    aliases: ["codecademy", "code academy"],
    url: "https://www.codecademy.com/",
    sourceCategory: "tutorial",
    domain: "tech-learning",
    authorityScore: 8,
    freshnessScore: 7,
    formatFitScore: 9,
    whySelected: "Structured beginner learning paths and interactive coding lessons.",
    supports: ["interactive learning", "beginner tutorial"],
    excerpt: "Use Codecademy for structured beginner lessons and skill-building roadmaps.",
  },
  {
    name: "Coursera",
    aliases: ["coursera"],
    url: "https://www.coursera.org/",
    sourceCategory: "tutorial",
    domain: "tech-learning",
    authorityScore: 8,
    freshnessScore: 7,
    formatFitScore: 9,
    whySelected: "Strong source for structured courses and guided beginner programs.",
    supports: ["course pathway", "structured learning"],
    excerpt: "Use Coursera to validate course-based learning paths and beginner-friendly programs.",
  },
  {
    name: "HackerRank",
    aliases: ["hackerrank", "hacker rank"],
    url: "https://www.hackerrank.com/",
    sourceCategory: "tutorial",
    domain: "tech-learning",
    authorityScore: 7,
    freshnessScore: 8,
    formatFitScore: 8,
    whySelected: "Useful for practice-oriented coding progression and challenge-based learning.",
    supports: ["practice", "coding challenges"],
    excerpt: "Use HackerRank to validate coding practice workflows and challenge-based skill building.",
  },
  {
    name: "LeetCode",
    aliases: ["leetcode", "leet code"],
    url: "https://leetcode.com/",
    sourceCategory: "tutorial",
    domain: "tech-learning",
    authorityScore: 7,
    freshnessScore: 8,
    formatFitScore: 8,
    whySelected: "Useful for interview practice and consistency-based coding repetition.",
    supports: ["practice", "interview preparation"],
    excerpt: "Use LeetCode to validate repetition-based practice and coding challenge recommendations.",
  },
  {
    name: "GitHub",
    aliases: ["github"],
    url: "https://github.com/",
    sourceCategory: "open-source",
    domain: "tech-learning",
    authorityScore: 8,
    freshnessScore: 8,
    formatFitScore: 8,
    whySelected: "Open-source repos validate tooling, starter projects, and ecosystem reality.",
    supports: ["implementation examples", "starter projects"],
    excerpt: "Use GitHub to find example repos and validate real-world ecosystem support.",
  },
];
